-- AAY BEE ELECTRICALS & CONSTRUCTION v2
create extension if not exists pgcrypto;
create table if not exists public.employees(id uuid primary key default gen_random_uuid(),auth_user_id uuid unique not null references auth.users(id) on delete cascade,employee_code text unique not null,full_name text not null,role text not null default 'user' check(role in('user','admin')),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.sites(id uuid primary key default gen_random_uuid(),site_name text unique not null,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.attendance(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.employees(id) on delete cascade,site_id uuid not null references public.sites(id),attendance_date date not null,status text not null check(status in('Present','Half Day','Absent')),marked_at timestamptz not null default now(),updated_at timestamptz not null default now(),updated_by uuid references public.employees(id),unique(employee_id,attendance_date));
create table if not exists public.attendance_logs(id uuid primary key default gen_random_uuid(),attendance_id uuid not null references public.attendance(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,site_id uuid not null references public.sites(id),old_status text not null,new_status text not null,changed_by uuid not null references public.employees(id),changed_at timestamptz not null default now());
create table if not exists public.employee_records(id uuid primary key default gen_random_uuid(),employee_code text unique not null,full_name text not null,phone text,email text,site_name text not null,designation text,joining_date date,aadhar_path text,created_by uuid references public.employees(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_requests(id uuid primary key default gen_random_uuid(),employee_code text not null,full_name text not null,phone text,email text,site_name text not null,designation text,joining_date date,aadhar_path text,status text not null default 'pending' check(status in('pending','approved','rejected')),submitted_by uuid not null references public.employees(id),approved_by uuid references public.employees(id),created_at timestamptz not null default now(),approved_at timestamptz);
create index if not exists idx_attendance_date on public.attendance(attendance_date);create index if not exists idx_logs_changed on public.attendance_logs(changed_at desc);create index if not exists idx_requests_status on public.employee_requests(status);
insert into public.sites(site_name) values('Main Site') on conflict(site_name) do nothing;
create or replace function public.is_admin() returns boolean language sql security definer stable set search_path=public as $$select exists(select 1 from public.employees where auth_user_id=auth.uid() and role='admin' and active=true);$$;
create or replace function public.my_employee_id() returns uuid language sql security definer stable set search_path=public as $$select id from public.employees where auth_user_id=auth.uid() and active=true limit 1;$$;
grant execute on function public.is_admin() to authenticated;grant execute on function public.my_employee_id() to authenticated;
create or replace function public.log_attendance_change() returns trigger language plpgsql security definer set search_path=public as $$begin if old.status is distinct from new.status or old.site_id is distinct from new.site_id then insert into public.attendance_logs(attendance_id,employee_id,site_id,old_status,new_status,changed_by) values(new.id,new.employee_id,new.site_id,old.status,new.status,coalesce(new.updated_by,public.my_employee_id()));end if;return new;end;$$;
drop trigger if exists trg_attendance_change on public.attendance;create trigger trg_attendance_change after update on public.attendance for each row execute function public.log_attendance_change();
alter table public.employees enable row level security;alter table public.sites enable row level security;alter table public.attendance enable row level security;alter table public.attendance_logs enable row level security;alter table public.employee_records enable row level security;alter table public.employee_requests enable row level security;
drop policy if exists emp_select on public.employees;create policy emp_select on public.employees for select to authenticated using(auth_user_id=auth.uid() or public.is_admin());
drop policy if exists sites_select on public.sites;create policy sites_select on public.sites for select to authenticated using(active=true or public.is_admin());
drop policy if exists att_select on public.attendance;create policy att_select on public.attendance for select to authenticated using(employee_id=public.my_employee_id() or public.is_admin());
drop policy if exists att_insert on public.attendance;create policy att_insert on public.attendance for insert to authenticated with check(employee_id=public.my_employee_id());
drop policy if exists att_update on public.attendance;create policy att_update on public.attendance for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists logs_select on public.attendance_logs;create policy logs_select on public.attendance_logs for select to authenticated using(public.is_admin());
drop policy if exists records_select on public.employee_records;create policy records_select on public.employee_records for select to authenticated using(true);
drop policy if exists records_admin_insert on public.employee_records;create policy records_admin_insert on public.employee_records for insert to authenticated with check(public.is_admin());
drop policy if exists records_admin_update on public.employee_records;create policy records_admin_update on public.employee_records for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists records_admin_delete on public.employee_records;create policy records_admin_delete on public.employee_records for delete to authenticated using(public.is_admin());
drop policy if exists req_select on public.employee_requests;create policy req_select on public.employee_requests for select to authenticated using(submitted_by=public.my_employee_id() or public.is_admin());
drop policy if exists req_insert on public.employee_requests;create policy req_insert on public.employee_requests for insert to authenticated with check(submitted_by=public.my_employee_id());
drop policy if exists req_update_admin on public.employee_requests;create policy req_update_admin on public.employee_requests for update to authenticated using(public.is_admin()) with check(public.is_admin());
-- Private Aadhaar bucket. Create it in Storage as a private bucket named aadhar-cards.
-- Storage policies below allow authenticated users to upload into a request folder and admins to read/manage files.
insert into storage.buckets(id,name,public) values('aadhar-cards','aadhar-cards',false) on conflict(id) do nothing;
drop policy if exists aadhar_upload on storage.objects;create policy aadhar_upload on storage.objects for insert to authenticated with check(bucket_id='aadhar-cards');
drop policy if exists aadhar_admin_read on storage.objects;create policy aadhar_admin_read on storage.objects for select to authenticated using(bucket_id='aadhar-cards' and public.is_admin());
drop policy if exists aadhar_admin_delete on storage.objects;create policy aadhar_admin_delete on storage.objects for delete to authenticated using(bucket_id='aadhar-cards' and public.is_admin());
