import {supabase} from './config.js';
let me=null,editingId=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function init(){const {data:{user}}=await supabase.auth.getUser();if(!user)return location.href='index.html';const {data:emp,error}=await supabase.from('employees').select('id,full_name,role,active').eq('auth_user_id',user.id).single();if(error||!emp||!emp.active)return location.href='index.html';me=emp;document.getElementById('userInfo').textContent=`Logged in as ${emp.full_name} (${emp.role})`;if(me.role==='admin'){document.getElementById('pendingCard').classList.remove('hidden');await loadPending()}else{document.getElementById('formTitle').textContent='Submit New Employee';document.getElementById('saveEmployeeBtn').textContent='Submit for Admin Approval'}await loadEmployees();}
async function upload(file,requestId){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${requestId}/${Date.now()}_${safe}`;const {error}=await supabase.storage.from('aadhar-cards').upload(path,file,{upsert:false});if(error)throw error;return path;}
async function loadEmployees(){const {data,error}=await supabase.from('employee_records').select('*').order('full_name');const body=document.getElementById('employeeBody');body.innerHTML='';if(error){body.innerHTML=`<tr><td colspan="9">${esc(error.message)}</td></tr>`;return}(data||[]).forEach(x=>body.insertAdjacentHTML('beforeend',`<tr><td>${esc(x.employee_code)}</td><td>${esc(x.full_name)}</td><td>${esc(x.phone)}</td><td>${esc(x.email)}</td><td>${esc(x.site_name)}</td><td>${esc(x.designation)}</td><td>${esc(x.joining_date)}</td><td>${x.aadhar_path?`<button class="view-aadhar" data-path="${esc(x.aadhar_path)}">View</button>`:'Not uploaded'}</td><td>${me.role==='admin'?`<button class="edit-btn" data-id="${x.id}">Edit</button> <button class="delete-btn danger" data-id="${x.id}">Delete</button>`:'Read only'}</td></tr>`));document.querySelectorAll('.edit-btn').forEach(b=>b.onclick=()=>editEmployee(b.dataset.id));document.querySelectorAll('.delete-btn').forEach(b=>b.onclick=()=>deleteEmployee(b.dataset.id));document.querySelectorAll('.view-aadhar').forEach(b=>b.onclick=()=>viewAadhar(b.dataset.path));}
async function loadPending(){const {data}=await supabase.from('employee_requests').select(`id,employee_code,full_name,phone,email,site_name,designation,joining_date,aadhar_path,created_at,submitted_by:employees!employee_requests_submitted_by_fkey(full_name)`).eq('status','pending').order('created_at');const body=document.getElementById('pendingBody');body.innerHTML='';(data||[]).forEach(x=>body.insertAdjacentHTML('beforeend',`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(x.employee_code)}</td><td>${esc(x.full_name)}</td><td>${esc(x.site_name)}</td><td>${esc(x.designation)}</td><td>${x.aadhar_path?'Uploaded':'None'}</td><td>${esc(x.submitted_by.full_name)}</td><td><button class="approve approve-btn" data-id="${x.id}">Approve</button> <button class="danger reject-btn" data-id="${x.id}">Reject</button></td></tr>`));document.querySelectorAll('.approve-btn').forEach(b=>b.onclick=()=>approve(b.dataset.id));document.querySelectorAll('.reject-btn').forEach(b=>b.onclick=()=>reject(b.dataset.id));}
async function approve(id){const {data:r,error}=await supabase.from('employee_requests').select('*').eq('id',id).single();if(error)return alert(error.message);const {error:e}=await supabase.from('employee_records').insert({employee_code:r.employee_code,full_name:r.full_name,phone:r.phone,email:r.email,site_name:r.site_name,designation:r.designation,joining_date:r.joining_date,aadhar_path:r.aadhar_path,created_by:r.submitted_by});if(e)return alert(e.message);await supabase.from('employee_requests').update({status:'approved',approved_by:me.id,approved_at:new Date().toISOString()}).eq('id',id);await loadPending();await loadEmployees();}
async function reject(id){await supabase.from('employee_requests').update({status:'rejected',approved_by:me.id,approved_at:new Date().toISOString()}).eq('id',id);await loadPending();}
async function submit(e){e.preventDefault();const f=document.getElementById('aadharFile').files[0];const base={employee_code:employeeCode.value.trim(),full_name:fullName.value.trim(),phone:phone.value.trim(),email:employeeEmail.value.trim(),site_name:siteName.value.trim(),designation:designation.value.trim(),joining_date:joiningDate.value||null};try{if(me.role==='user'){const {data:req,error}=await supabase.from('employee_requests').insert({...base,submitted_by:me.id}).select('id').single();if(error)throw error;if(f){const path=await upload(f,req.id);await supabase.from('employee_requests').update({aadhar_path:path}).eq('id',req.id)}message.textContent='Employee submitted for admin approval.'}else{if(editingId){const {error}=await supabase.from('employee_records').update({...base,aadhar_path:undefined}).eq('id',editingId);if(error)throw error;message.textContent='Employee updated.'}else{const {data:r,error}=await supabase.from('employee_records').insert({...base,created_by:me.id}).select('id').single();if(error)throw error;if(f){const path=await upload(f,r.id);await supabase.from('employee_records').update({aadhar_path:path}).eq('id',r.id)}message.textContent='Employee added.'}resetForm();await loadEmployees()}}catch(err){message.textContent=err.message}}
async function editEmployee(id){const {data:x}=await supabase.from('employee_records').select('*').eq('id',id).single();if(!x)return;editingId=id;employeeId.value=id;employeeCode.value=x.employee_code;fullName.value=x.full_name;phone.value=x.phone||'';employeeEmail.value=x.email||'';siteName.value=x.site_name;designation.value=x.designation||'';joiningDate.value=x.joining_date||'';document.getElementById('formTitle').textContent='Edit Employee';document.getElementById('saveEmployeeBtn').textContent='Save Changes';document.getElementById('cancelEditBtn').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function deleteEmployee(id){if(!confirm('Delete this employee record?'))return;const {error}=await supabase.from('employee_records').delete().eq('id',id);message.textContent=error?error.message:'Employee deleted.';await loadEmployees()}
async function viewAadhar(path){const {data,error}=await supabase.storage.from('aadhar-cards').createSignedUrl(path,300);if(error)return alert(error.message);window.open(data.signedUrl,'_blank')}
function resetForm(){editingId=null;document.getElementById('employeeForm').reset();document.getElementById('employeeId').value='';document.getElementById('formTitle').textContent=me.role==='admin'?'Add Employee':'Submit New Employee';document.getElementById('saveEmployeeBtn').textContent=me.role==='admin'?'Submit':'Submit for Admin Approval';document.getElementById('cancelEditBtn').classList.add('hidden')}
document.getElementById('employeeForm').addEventListener('submit',submit);document.getElementById('cancelEditBtn').onclick=resetForm;document.getElementById('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.href='index.html'};init();
